# Generated by Django 5.2.5 on 2025-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
