# Generated by Django 5.2.5 on 2025-08-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0002_stock"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="Clients",
        ),
        migrations.RenameModel(
            old_name="Stock",
            new_name="Stocks",
        ),
    ]
