# Generated by Django 5.2.5 on 2025-08-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0003_rename_client_clients_rename_stock_stocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Units",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=20)),
                ("unit_shortcut", models.CharField(max_length=2)),
                ("description", models.TextField()),
            ],
        ),
    ]
