# Generated by Django 5.2.5 on 2025-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0005_carriers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carriers",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
