# Generated by Django 5.2.5 on 2025-08-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders_app",
            "0006_alter_carriers_description_alter_clients_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Trucks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_type", models.CharField(max_length=30)),
                ("truck_capacity", models.SmallIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "carrier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trucks",
                        to="orders_app.carriers",
                    ),
                ),
            ],
        ),
    ]
