# Generated by Django 5.2.5 on 2025-08-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0007_trucks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drivers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=100)),
                (
                    "carrier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="orders_app.carriers",
                    ),
                ),
            ],
        ),
    ]
