# Generated by Django 5.2.5 on 2025-08-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0008_drivers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TruckCapacities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_capacity", models.SmallIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders_app_truck_capacities",
            },
        ),
        migrations.CreateModel(
            name="TruckTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_type", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders_app_truck_types",
            },
        ),
        migrations.RemoveField(
            model_name="trucks",
            name="truck_capacity",
        ),
        migrations.RemoveField(
            model_name="trucks",
            name="truck_type",
        ),
        migrations.AddField(
            model_name="trucks",
            name="truck_capacity_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trucks",
                to="orders_app.truckcapacities",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trucks",
            name="truck_type_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trucks",
                to="orders_app.trucktypes",
            ),
            preserve_default=False,
        ),
    ]
