# Generated by Django 5.2.5 on 2025-08-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0009_truckcapacities_trucktypes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drivers",
            old_name="carrier_id",
            new_name="carrier",
        ),
        migrations.RenameField(
            model_name="trucks",
            old_name="carrier_id",
            new_name="carrier",
        ),
        migrations.RenameField(
            model_name="trucks",
            old_name="truck_capacity_id",
            new_name="truck_capacity",
        ),
        migrations.RenameField(
            model_name="trucks",
            old_name="truck_type_id",
            new_name="truck_type",
        ),
    ]
