# Generated by Django 5.2.5 on 2025-08-29 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0010_rename_carrier_id_drivers_carrier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("base_unit_weight", models.SmallIntegerField(null=True)),
                ("report_unit_ratio", models.SmallIntegerField(null=True)),
                ("palette_volume", models.SmallIntegerField(null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "base_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_unit",
                        to="orders_app.units",
                    ),
                ),
                (
                    "report_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_unit",
                        to="orders_app.units",
                    ),
                ),
            ],
        ),
    ]
