# Generated by Django 5.2.5 on 2025-08-30 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0011_products"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Carriers",
            new_name="Carrier",
        ),
        migrations.RenameModel(
            old_name="Clients",
            new_name="Client",
        ),
        migrations.RenameModel(
            old_name="Drivers",
            new_name="Driver",
        ),
        migrations.RenameModel(
            old_name="Stocks",
            new_name="Stock",
        ),
        migrations.RenameModel(
            old_name="Trucks",
            new_name="Truck",
        ),
        migrations.RenameModel(
            old_name="TruckCapacities",
            new_name="TruckCapacity",
        ),
        migrations.RenameModel(
            old_name="TruckTypes",
            new_name="TruckType",
        ),
        migrations.RenameModel(
            old_name="Units",
            new_name="Unit",
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("base_unit_weight", models.SmallIntegerField()),
                ("report_unit_ratio", models.SmallIntegerField(null=True)),
                ("palette_volume", models.SmallIntegerField(null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "base_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_unit",
                        to="orders_app.unit",
                    ),
                ),
                (
                    "report_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_unit",
                        to="orders_app.unit",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
