# Generated by Django 5.2.5 on 2025-09-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0012_rename_carriers_carrier_rename_clients_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="report_unit",
        ),
        migrations.RemoveField(
            model_name="product",
            name="report_unit_ratio",
        ),
        migrations.AddField(
            model_name="unit",
            name="to_kg_factor",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="How many kilograms are in 1 unit of this type.",
                max_digits=12,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="base_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="orders_app.unit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_unit_weight",
            field=models.DecimalField(
                decimal_places=6,
                help_text="For example: 1 pcs = 0.5 kg, 1 kg = 1.0, 1 ton = 1000.0",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_shortcut",
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
