# Generated by Django 5.2.5 on 2025-09-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0014_order_orderitem_order_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="base_unit",
        ),
        migrations.RemoveField(
            model_name="product",
            name="base_unit_weight",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="description",
        ),
        migrations.AddField(
            model_name="unit",
            name="is_weight_based",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="to_kg_factor",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Conversion factor to kilograms (if weight-based). For non-weight units, leave as 1.",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kg_per_unit",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="For example: 1 pcs = 0.5 kg, 1 kg = 1.0, 1 ton = 1000.0",
                        max_digits=12,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="orders_app.product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders_app.unit",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "unit")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_units",
            field=models.ManyToManyField(
                related_name="product_units",
                through="orders_app.ProductUnit",
                to="orders_app.unit",
            ),
        ),
    ]
