# Generated by Django 5.2.5 on 2025-09-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0015_remove_product_base_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kg_per_unit",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Например: 1 шт = 0.5 кг, 1 кг = 1.0, 1 ton = 1000.0",
                        max_digits=12,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="orders_app.product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders_app.unit",
                    ),
                ),
            ],
            options={
                "db_table": "orders_app_product_weights",
                "unique_together": {("product", "unit")},
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="product_units",
            field=models.ManyToManyField(
                related_name="product_units",
                through="orders_app.ProductWeight",
                to="orders_app.unit",
            ),
        ),
        migrations.DeleteModel(
            name="ProductUnit",
        ),
    ]
