# Generated by Django 5.2.5 on 2025-09-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0016_productweight_alter_product_product_units_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="Customer",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="client_name",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="client",
            new_name="customer",
        ),
    ]
