# Generated by Django 5.2.5 on 2025-09-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0017_rename_client_customer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Unit",
            new_name="AppUnit",
        ),
        migrations.AlterModelTable(
            name="appunit",
            table="orders_app_units",
        ),
    ]
