# Generated by Django 5.2.5 on 2025-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0018_rename_unit_appunit_alter_appunit_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="driving_scheme",
            field=models.FileField(
                blank=True, null=True, upload_to="orders_app/schemas/"
            ),
        ),
    ]
