# Generated by Django 5.2.5 on 2025-09-01 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0019_stock_address_stock_driving_scheme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productweight",
            old_name="unit",
            new_name="product_unit",
        ),
        migrations.AlterUniqueTogether(
            name="productweight",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_units",
        ),
        migrations.AddField(
            model_name="product",
            name="product_unit",
            field=models.ManyToManyField(
                through="orders_app.ProductWeight", to="orders_app.appunit"
            ),
        ),
        migrations.AlterField(
            model_name="productweight",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders_app.product"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productweight",
            unique_together={("product", "product_unit")},
        ),
    ]
